apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-system
    environment: Development
  name: notification-system
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: notification-system
  sessionAffinity: None
  type: ClusterIP
